apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: children
    repoURL: https://github.com/jannfis/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
